# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0000000000etc
  jwt_secret: 0000000000etc
  taxi_api_key: 0000000000etc
  lyft_bearer_token: 0000000000etc
  uber_token: 0000000000etc
test:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  jwt_secret: <%= Figaro.env.jwt_secret %>
  taxi_api_key: <%= Figaro.env.taxi_api_key %>
  lyft_bearer_token: <%= Figaro.env.lyft_bearer_token %>
  uber_token: <%= Figaro.env.uber_token %>  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
